name: Check examples

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: install rust
        uses: actions-rs/toolchain@v1.0.0
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Run hello world
        run: |
          cd integrations/rust/examples/hello-world
          cargo run
      - name: Run early exit
        run: |
          cd integrations/rust/examples/early-exit
          cargo run
      - name: Run handling errors
        run: |
          cd integrations/rust/examples/handling-errors
          cargo run
      - name: Run host functions
        run: |
          cd integrations/rust/examples/host-functions
          cargo run
      - name: Run passing data
        run: |
          cd integrations/rust/examples/passing-data
          cargo run
