name: Check examples

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: install rust
        uses: actions-rs/toolchain@v1.0.0
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Run Rust examples
        run: |
          cd integrations/rust/examples/hello-world
          cargo run
